/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 366d80a937173318e4a73a5826a5ef4c)
interface __BaseEnv_Env {
	VAULT_BUCKET: R2Bucket;
	VAULT_DB: D1Database;
	ASSETS: Fetcher;
	ENVIRONMENT: "production";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
